import type { Metadata } from 'next'
import '../styles/global.css';


export const metadata: Metadata = {
  title: 'Hono | nextjs',
  description: 'Generated by hono'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className='flex max-w-4/5 justify-center'>{children}</body>
    </html>
  )
}
